### ISSUE TITLE
timstof.dll

### ISSUE THREAD

**Issue by im281** [mafreitas/tdf2mzml#1]
Getting these errors indicating that the methods don't exist in the Bruker DLL? Is this a versioning issue?

Exception has occurred: AttributeError
function 'tims_read_pasef_profile_msms' not found
  File "C:\Git\tdf2mzml-master\tdf2mzml-master\timsdata.py", line 33, in <module>
    dll.tims_read_pasef_profile_msms.argtypes = [ c_uint64, POINTER(c_int64), c_uint32, MSMS_PROFILE_SPECTRUM_FUNCTOR ]
  File "C:\Git\tdf2mzml-master\tdf2mzml-master\tdf2mzml.py", line 26, in <module>
    import timsdata as timsdata

**Comment by mafreitas** [comment]
Can you provide more details on the environment?  It could be related to location of the lib file.  Also you try the docker image to see if it works.
