### ISSUE TITLE
conversion of diaPASEF data

### ISSUE THREAD

**Issue by cjhjhj** [mafreitas/tdf2mzml#10]
Hello there,
I could successfully convert a DDA dataset, but failed the conversion of DIA dataset with the following error,
```
  File "tdf2mzml.py", line 983, in <module>
    main()
  File "tdf2mzml.py", line 978, in main
    write_mzml(args)
  File "tdf2mzml.py", line 60, in wrap
    ret = f(*args)
  File "tdf2mzml.py", line 819, in write_mzml
    mzml_data_struct['data_dict'] = get_spectrum_dict(mzml_data_struct)
  File "tdf2mzml.py", line 271, in get_spectrum_dict
    precursor_frame_id)
sqlite3.OperationalError: no such table: Precursors
```
Could you please let me know whether tdf2mzml can convert Bruker's diaPASEF data from a timsTOF instrument? 
Thank you.

**Comment by mafreitas** [comment]
There is a branch “dia” where we were testing support for dia files.

**Comment by cjhjhj** [comment]
Thanks a lot for your quick response. I have cloned the "dia" branch and I am testing now (so far, it looks okay).

**Comment by mafreitas** [comment]
Good, but please give any feedback.  Eventually would like to merge this into main.

**Comment by cjhjhj** [comment]
The conversion was done using tdf2mzml. However, I came across an error when I tested the converted mzml file with DIA-NN. 
The Windows version of DIA-NN gave the following message and finished without any identification result,
```WARNING: incorrectly recorded isolation window margins```
It seems that there's no 'isolation window' field in MS2 scans of the converted mzml file. It would be great if you could check it and fix the problem.

**Comment by mafreitas** [comment]
Can you share the mzML?  I am reaching out to the developers of DIA-NN to see if we can figure out the incompatibility.  You can also add your comments to this issue on their GitHub repository as well.

**Comment by cjhjhj** [comment]
The file size is too big (~2GB). I'm not sure how I can share the file with you.

**Comment by mafreitas** [comment]
If you email me directly at my work address, I can provide a shared drive link.

**Comment by jsnedeco** [comment]
Was this addressed? I'm interesting in something similar.

**Comment by mafreitas** [comment]
Yes, I would test it out, and if it doesn't work, we can address.
