### ISSUE TITLE
`pip install -r requirements` fails with python 3.9 because out of date pandas/numpy req

### ISSUE THREAD

**Issue by jtprince** [mafreitas/tdf2mzml#16]
Requirements failed to install (`pip -r requirements`) with **python 3.9.9** on arch linux (5.17.4-arch1-1) with a clean virtualenv.

The requirements installation had no errors using **python 3.8**.

Relevant output (for anyone that gets a similar error):
```
...
gcc: numpy/random/mtrand/mtrand.c
            numpy/random/mtrand/mtrand.c: In function ‘__Pyx_modinit_type_init_code’:
            numpy/random/mtrand/mtrand.c:43635:33: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
            43635 |   __pyx_type_6mtrand_RandomState.tp_print = 0;
...

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure

      × Encountered error while trying to install package.
      ╰─> numpy

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
```

To ameliorate: pin the latest known compatible python version on the README or update requirements.txt with more recent packages? Thanks!

**Comment by mafreitas** [comment]
Thanks, I will update the readme.  This is why I prefer containerized and thus a well-controlled environment.
