### ISSUE TITLE
GLIBC_2.29 on Ubuntu 18.04

### ISSUE THREAD

**Issue by im281** [mafreitas/tdf2mzml#2]
Do I need to recompile?

Exception has occurred: OSError
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./libtimsdata.so)
  File "/home/ubuntu/apps/tdf2mzml/app/timsdata.py", line 16, in <module>
    dll = cdll.LoadLibrary(libname)
  File "/home/ubuntu/apps/tdf2mzml/app/tdf2mzml.py", line 26, in <module>
    import timsdata as timsdata

**Comment by mafreitas** [comment]
This is known issue with the SDK.  It was compiled with the latest version of Ubuntu (bionic).  So it needs that version with the system GBLIC that has been updated.  This issue is one reason for using the docker image as it has the latest ubuntu.
